services:
  monitoring_api:
    image: ghcr.io/dvvtech/monitoring-platform:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Prod                 
    networks:
      - public-network5    
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:      
        - "traefik.enable=true"
        - "traefik.http.routers.monitoring.rule=Host(`monitoring.cloud-platform.pro`)"
        - "traefik.http.routers.monitoring.entrypoints=websecure"
        - "traefik.http.routers.monitoring.tls.certresolver=letsencrypt"
        - "traefik.http.services.monitoring.loadbalancer.server.port=8080"

networks:
  public-network5:
    external: true    